version: '3.1'

services:
  Uvideo-pg:
    image: mongo:4.0.4
    container_name: Uvideo-pg
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - mongo:/data/db
    ports:
      - 27017:27017

volumes:
  mongo:
      